### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by jle-quel** [jle-quel/Taskmaster#15]
```
Launch server and client
status all
status ls
```

/Users/jle-quel/Documents/Taskmaster/src/server/controllers/status.js:49
				} else status.push(`${processGroupLength === 1 ? '' : processGroupName + ':'}${processName}\t${_process.status}\t\t${_process.status === 'STOPPED' && !_process.pid ? 'Not started': ''}`)
				                                                      ^

ReferenceError: processGroupName is not defined
    at Object.keys.map (/Users/jle-quel/Documents/Taskmaster/src/server/controllers/status.js:49:59)
    at Array.map (<anonymous>)
    at processNamesOrGroupName.map (/Users/jle-quel/Documents/Taskmaster/src/server/controllers/status.js:43:53)
    at Array.map (<anonymous>)
    at Object.one (/Users/jle-quel/Documents/Taskmaster/src/server/controllers/status.js:39:26)
    at Object.status (/Users/jle-quel/Documents/Taskmaster/src/server/controllers/index.js:10:111)
    at Socket.socket.on (/Users/jle-quel/Documents/Taskmaster/src/server/index.js:51:27)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)

**Comment by mi-mazouz** [comment]
~/Projects/Taskmaster mi-mazouz---> npm run start:server                                                                                                                      21:32

> taskmaster@1.0.0 start:server /Users/mimazouz/Projects/Taskmaster
> node ./src/server/index.js ./config.json

taskmaster: error in creation of the logger
events.js:112
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:596:16)
    at Object.keys.map (/Users/mimazouz/Projects/Taskmaster/src/server/controllers/stop.js:21:17)
    at Array.map (<anonymous>)
    at Object.keys.map (/Users/mimazouz/Projects/Taskmaster/src/server/controllers/stop.js:12:46)
    at Array.map (<anonymous>)
    at Object.all (/Users/mimazouz/Projects/Taskmaster/src/server/controllers/stop.js:11:27)
    at Object.all (/Users/mimazouz/Projects/Taskmaster/src/server/controllers/restart.js:12:15)
    at Object.restart (/Users/mimazouz/Projects/Taskmaster/src/server/controllers/index.js:19:57)
    at Socket.socket.on (/Users/mimazouz/Projects/Taskmaster/src/server/index.js:51:27)
    at Socket.emit (events.js:127:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taskmaster@1.0.0 start:server: `node ./src/server/index.js ./config.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the taskmaster@1.0.0 start:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌─────────────────────────────────────────────────────────────┐
│                   npm update check failed                   │
│             Try running with sudo or get access             │
│            to the local update config store via             │
│ sudo chown -R $USER:$(id -gn $USER) /Users/mimazouz/.config │
└─────────────────────────────────────────────────────────────┘
~/Projects/Taskmaster mi-mazouz--->                                                                                                                                           21:32
